# /home/roger/regolith-nix-starter-config/hosts/regolith/home.nix
{ pkgs, lib, ... }: # <-- Make sure 'lib' is in the arguments if not already

{
  home.stateVersion = "24.05";

  home.packages = with pkgs; [
    hello
    vlc
    zsh-powerlevel10k  # Install Powerlevel10k theme
    meslo-lgs-nf       # Install a Nerd Font for Powerlevel10k glyphs
    lsd                # Ensure lsd is installed for aliases
  ];

  programs.zsh = {
    enable = true;
    enableCompletion = true;

    oh-my-zsh = {
      enable = true;
      #theme = "powerlevel10k/powerlevel10k";
      plugins = [
        "git"   
      ];
    };

    autosuggestion = {
      enable = true;
    };
    syntaxHighlighting = {
      enable = true;
    };

    # All your custom Zsh initialization goes here, using lib.mkOrder and lib.mkMerge
    initContent = let
      # 1. Powerlevel10k Instant Prompt (Very Early Initialization: 500)
      # This MUST run as early as possible.
      p10kInstantPrompt = lib.mkOrder 500 ''
        # Manually source Powerlevel10k theme early.
        # We find its path in the Nix store via the installed package.
        # This bypasses the ohMyZsh.theme option.
        source "$(find ${pkgs.zsh-powerlevel10k}/share -name "powerlevel10k.zsh-theme" | head -n 1)"

        # Generated by Powerlevel10k instant prompt wizard.
        # To restart it, type `p10k configure`.
        if [[ -r "''${XDG_CACHE_HOME:-\''$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh" ]]; then
          source "''${XDG_CACHE_HOME:-\''$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh"
        fi
      '';

      # 2. General Configuration (Default Order: 1000)
      # This section runs after core Zsh and Oh My Zsh have initialized.
      generalConfig = lib.mkOrder 1000 ''
        # --- Zsh Options ---
        setopt AUTO_CD       # Change directory by typing only the directory name
        setopt EXTENDED_GLOB # Extended globbing (e.g., recursive wildcards)

        # LSD aliases
        alias ls='lsd'
        alias l='ls -l'
        alias la='ls -a'
        alias lla='ls -la'
        alias lt='ls --tree'

        # FZF integration (sourced after everything else is ready)
        # Home Manager's programs.fzf.enable=true usually handles this,
        # but if you need to manually source it for some reason, here's where it goes.
        # source <(fzf --zsh);

        # Zsh history settings
        HISTFILE=~/.zsh_history;
        HISTSIZE=10000;
        SAVEHIST=10000;
        setopt appendhistory;
      '';

      # 3. Powerlevel10k Configuration Sourcing (Last to run: 1500)
      # This sources your generated ~/.p10k.zsh file after everything else is set up.
      p10kConfigSource = lib.mkOrder 1500 ''
        if [[ -f "$HOME/.p10k.zsh" ]]; then
          source "$HOME/.p10k.zsh"
        fi
      '';
    in
      # Merge all ordered configuration blocks
      lib.mkMerge [
        p10kInstantPrompt
        generalConfig
        p10kConfigSource
      ];
  };

  # Ensure your custom ~/.p10k.zsh is managed
  home.file.".p10k.zsh".source = ./p10k.zsh;

  # Add fzf via Home Manager's dedicated module (highly recommended for clean integration)
  programs.fzf.enable = true;
  # Note: If programs.fzf.enable = true; is used, you usually don't need `source <(fzf --zsh);`
  # in your initContent, as Home Manager handles the sourcing.
  # I've commented it out in generalConfig above to reflect this.
}
